name: Cancel Older Job
on:
  push:
    branches:
      - "*"
    tags:
      - "!*"
  pull_request:
jobs:
  Cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Cancel Older Workflow
        uses: yellowmegaman/gh-build-canceller@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflows_filter: "Docs Update"
