# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches:
      - "!master"
    tags:
      - "*"

jobs:
  Release:
    container: electronuserland/builder:wine
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14.x
      - uses: actions/cache@v2.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          : git symbolic-ref -q --short HEAD || : git describe --tags --exact-match
          rm -rf ~/.wine && mkdir -p ../.wine
          export WINEPREFIX=$(readlink -f $PWD/../.wine)
          winecfg
          export orig_pwd=$PWD
          npm install -g pnpm
          pnpm install -r
          pnpm run build && pnpm run format
          cp -r docs/ electron/
          cd electron/
          pnpm run build
          node ./node_modules/electron-builder/out/cli/cli.js -wl --x64 --arm64
          mv artifact/Aria2-WebUI-Electron\ Setup\ *.*.*.exe          $(ls artifact/Aria2-WebUI-Electron\ Setup\ *.*.*.exe | tr ' ' -)
          mv artifact/Aria2-WebUI-Electron\ Setup\ *.*.*.exe.blockmap $(ls artifact/Aria2-WebUI-Electron\ Setup\ *.*.*.exe.blockmap | tr ' ' -)
          cd artifact/
          tar -acvf win-portable.tar.zst win-unpacked/*
          tar -acvf linux-portable.tar.zst linux-unpacked/*
          tar -acvf win-arm64-portable.tar.zst win-arm64-unpacked/*
          tar -acvf linux-arm64-portable.tar.zst linux-arm64-unpacked/*
      - name: Upload Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            electron/artifact/win-portable.tar.zst
            electron/artifact/linux-portable.tar.zst
            electron/artifact/win-arm64-portable.tar.zst
            electron/artifact/linux-arm64-portable.tar.zst
            electron/artifact/Aria2-WebUI-Electron-Setup-*.*.*.exe
            electron/artifact/Aria2-WebUI-Electron-Setup-*.*.*.exe.blockmap
            electron/artifact/Aria2-WebUI-Electron-*.*.*-arm64.pacman
            electron/artifact/Aria2-WebUI-Electron-*.*.*.pacman
            electron/artifact/Aria2-WebUI-Electron_*.*.*_amd64.deb
            electron/artifact/Aria2-WebUI-Electron_*.*.*_arm64.deb
            electron/artifact/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
