# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docs Update

on:
  push:
    branches: [master]
    tags-ignore:
      - "*"

jobs:
  Update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: "0"
      - name: Use Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x
      - uses: actions/cache@main
        with:
          path: ~/workspace/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ ! $(git rev-parse HEAD) = $(cat docs/current-commit) ] && grep '(DOCS UPDATE)' >/dev/null ; then
            npm install -g pnpm
            pnpm i
            pnpm run build
            ./tools/update.sh
          else
            echo 'Do nothing'
          fi
